// src/hooks/useQRPayment.ts
import { useState } from 'react'
import { useNotification } from '@/contexts/NotificationContext'
import { PaymentMethod } from '@/types/payment'

export function useQRPayment() {
  const [isProcessing, setIsProcessing] = useState(false)
  const [isOrderModalOpen, setIsOrderModalOpen] = useState(false)
  const { addNotification } = useNotification()

  // QR payment method configuration
  const paymentMethod: PaymentMethod = {
    type: 'qris',
    paymentMethodName: 'QRIS - Semua E-Wallet & Bank',
    qrCode: '/qr-dummy.png', // Static untuk sekarang, nanti dari Midtrans
    instructions: [
      'Buka aplikasi e-wallet atau mobile banking Anda (GoPay, OVO, Dana, atau aplikasi bank yang mendukung QRIS).',
      'Pilih menu "Scan QR" atau "Bayar dengan QRIS" di aplikasi Anda.',
      'Scan kode QR yang ditampilkan di atas atau masukkan kode pembayaran secara manual.',
      'Pastikan nominal pembayaran sesuai dengan total pesanan Anda.',
      'Setelah melakukan pembayaran, simpan bukti transaksi (screenshot atau foto).',
      'Klik tombol "Pembayaran Selesai" di bawah untuk mengkonfirmasi bahwa Anda telah melakukan pembayaran.',
      'Proses verifikasi pembayaran biasanya memakan waktu 5-10 menit, namun pada kondisi tertentu dapat memakan waktu hingga 1×24 jam. Mohon menunggu hingga status pesanan Anda berubah.',
      'Jika ada kendala atau pembayaran tidak terverifikasi, silakan hubungi tim support melalui kontak yang tersedia di bawah.'
    ]
  }

  const handlePaymentComplete = () => {
    setIsProcessing(true)
    
    setTimeout(() => {
      setIsProcessing(false)
      setIsOrderModalOpen(true)
      
      addNotification({
        title: 'Pesanan Siap Diambil',
        message: 'Pesanan #NL001 sudah siap untuk diambil di counter utama',
        time: 'Baru saja',
        isRead: false,
        type: 'order'
      })
    }, 2000)
  }

  // Future: Easy switch to different QR providers
  const switchToProvider = (provider: 'qris' | 'gopay' | 'ovo' | 'shopeepay') => {
    const providerConfigs = {
      qris: {
        type: 'qris' as const,
        paymentMethodName: 'QRIS - Semua E-Wallet & Bank',
        instructions: paymentMethod.instructions
      },
      gopay: {
        type: 'gopay' as const,
        paymentMethodName: 'GoPay',
        instructions: [
          'Buka aplikasi Gojek/GoPay di smartphone Anda.',
          'Tap menu "Bayar" pada beranda aplikasi.',
          'Pilih "Scan QR Code" dan arahkan kamera ke QR code di atas.',
          // ... GoPay specific instructions
        ]
      },
      ovo: {
        type: 'ovo' as const,
        paymentMethodName: 'OVO',
        instructions: [
          'Buka aplikasi OVO di smartphone Anda.',
          'Tap "Scan" pada beranda aplikasi.',
          'Arahkan kamera ke QR code yang ditampilkan di atas.',
          // ... OVO specific instructions
        ]
      },
      shopeepay: {
        type: 'shopeepay' as const,
        paymentMethodName: 'ShopeePay',
        instructions: [
          'Buka aplikasi Shopee di smartphone Anda.',
          'Tap menu "ShopeePay" di beranda.',
          'Pilih "Scan & Pay" dan arahkan kamera ke QR code.',
          // ... ShopeePay specific instructions
        ]
      }
    }
    
    return providerConfigs[provider]
  }

  // Future: Midtrans QR generation
  const switchToMidtrans = () => {
    return {
      type: 'midtrans' as const,
      paymentMethodName: 'Midtrans QR Payment',
      qrCode: null, // Will be generated by Midtrans
      instructions: []
    }
  }

  return {
    paymentMethod,
    isProcessing,
    isOrderModalOpen,
    setIsOrderModalOpen,
    handlePaymentComplete,
    switchToProvider,
    switchToMidtrans
  }
}